spring:

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 176c8918b1efd6
    password: fe58fc0d507b56
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/impact
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/master.xml

logging:
  level:
    liquibase: DEBUG


jwt:
  secret: eferfcedcwed343fed
