### GET request to example server
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "uuid": "8ca66331-ae12-42a5-b644-f3219dffa891",
  "firstName": "Steve",
  "lastName": "Rogers",
  "password": "230ASD#:",
  "cpf": "69351719030",
  "email": "steve@avenger.com",
  "phoneNumber": "123456789",
  "birthday": "1918-06-4",
  "role": "ADMIN",
  "files": [
    {
      "uuid": "83fe6659-79b6-41b0-be66-5979b661b084",
      "name": "Captain Avatar",
      "path": "https://avatarfiles.alphacoders.com/167/167457.jpg",
      "type": "JPEG",
      "_edited": true,
      "active": true
    }
  ],
  "_edited": true,
  "active": true
}

###

### GET request to example server
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "steve@avenger.com",
  "password": "230ASD#:"
}

> {%
    client.global.set("jwt", response.body.token)
%}

###

### GET request to example server
GET http://localhost:8080/api/users/32
Authorization: Bearer {{jwt}}

###

### GET request to example server
GET http://localhost:8080/api/users
Authorization: Bearer {{jwt}}

###